// data.js — sushi menu (pure data, no DOM); name/kana/desc are structured {zh,py,en} fields
export const MENU = [
  { id: "tuna-nigiri",  price: 6,
    name: { zh: "金枪鱼握寿司", py: ["jīn","qiāng","yú","wò","shòu","sī"], en: "Tuna Nigiri" },
    kana: { zh: "金枪鱼", py: ["jīn","qiāng","yú"], en: "Maguro" },
    desc: { zh: "蓝鳍金枪鱼，盖在手捏米饭上。", py: ["lán","qí","jīn","qiāng","yú","gài","zài","shǒu","niē","mǐ","fàn","shàng"], en: "Bluefin over hand-pressed rice." } },
  { id: "salmon-nigiri", price: 5,
    name: { zh: "三文鱼握寿司", py: ["sān","wén","yú","wò","shòu","sī"], en: "Salmon Nigiri" },
    kana: { zh: "三文鱼", py: ["sān","wén","yú"], en: "Sake" },
    desc: { zh: "肥美三文鱼，刷上一层甜酱油。", py: ["féi","měi","sān","wén","yú","shuā","shàng","yì","céng","tián","jiàng","yóu"], en: "Buttery salmon, brushed with nikiri." } },
  { id: "dragon-roll", price: 14,
    name: { zh: "龙卷", py: ["lóng","juǎn"], en: "Dragon Roll" },
    kana: { zh: "龙", py: ["lóng"], en: "Ryu" },
    desc: { zh: "鳗鱼与牛油果，鳞片状如游龙。", py: ["mán","yú","yǔ","niú","yóu","guǒ","lín","piàn","zhuàng","rú","yóu","lóng"], en: "Eel & avocado, scaled like a dragon." } },
  { id: "spicy-tuna", price: 9,
    name: { zh: "辣金枪鱼卷", py: ["là","jīn","qiāng","yú","juǎn"], en: "Spicy Tuna Roll" },
    kana: { zh: "微辣", py: ["wēi","là"], en: "Pirikara" },
    desc: { zh: "金枪鱼碎、辣油，口感爽脆。", py: ["jīn","qiāng","yú","suì","là","yóu","kǒu","gǎn","shuǎng","cuì"], en: "Chopped tuna, chili oil, crunch." } },
  { id: "uni-gunkan", price: 12,
    name: { zh: "海胆军舰", py: ["hǎi","dǎn","jūn","jiàn"], en: "Uni Gunkan" },
    kana: { zh: "海胆", py: ["hǎi","dǎn"], en: "Uni" },
    desc: { zh: "海胆军舰卷——再合适不过。", py: ["hǎi","dǎn","jūn","jiàn","juǎn","zài","hé","shì","bú","guò"], en: "Sea urchin battleship — fitting." } },
  { id: "tamago", price: 4,
    name: { zh: "玉子烧", py: ["yù","zǐ","shāo"], en: "Tamago" },
    kana: { zh: "玉子", py: ["yù","zǐ"], en: "Tamago" },
    desc: { zh: "层层叠叠的甜味厚蛋烧。", py: ["céng","céng","dié","dié","de","tián","wèi","hòu","dàn","shāo"], en: "Sweet layered omelette." } },
  { id: "edamame", price: 5,
    name: { zh: "毛豆", py: ["máo","dòu"], en: "Edamame" },
    kana: { zh: "毛豆", py: ["máo","dòu"], en: "Edamame" },
    desc: { zh: "海盐风味毛豆。", py: ["hǎi","yán","fēng","wèi","máo","dòu"], en: "Sea-salted soybeans." } },
  { id: "miso-soup", price: 3,
    name: { zh: "味噌汤", py: ["wèi","cēng","tāng"], en: "Miso Soup" },
    kana: { zh: "味噌", py: ["wèi","cēng"], en: "Miso" },
    desc: { zh: "高汤、豆腐、葱花。", py: ["gāo","tāng","dòu","fu","cōng","huā"], en: "Dashi, tofu, scallion." } },
];
