// data.js — Spinning Dragon Sushi menu (pure data, no DOM).
// Each text field is { zh, py (phrase pinyin), en }. Generated from the supplied asset pack.
export const MENU = [
  { id: "watermelon_extreme_roll", price: 3, image: "assets/menu/watermelon_extreme_roll.webp",
    category: { zh: "招牌卷", py: "Zhāopái Juǎn", en: "Signature Rolls" },
    name:     { zh: "西瓜极限卷", py: "Xīguā Jíxiàn Juǎn", en: "Watermelon Extreme Roll" },
    desc:     { zh: "西瓜、黄瓜和辣味酱，清爽多汁。", py: "Xīguā, huángguā hé làwèi jiàng, qīngshuǎng duōzhī.", en: "Fresh watermelon, cucumber, and spicy sauce with a juicy crunch." } },
  { id: "melting_chocolate_roll", price: 3, image: "assets/menu/melting_chocolate_roll.webp",
    category: { zh: "招牌卷", py: "Zhāopái Juǎn", en: "Signature Rolls" },
    name:     { zh: "融化巧克力卷", py: "Rónghuà Qiǎokèlì Juǎn", en: "Melting Chocolate Roll" },
    desc:     { zh: "浓郁巧克力、奶油夹心和脆粒。", py: "Nóngyù qiǎokèlì, nǎiyóu jiāxīn hé cuìlì.", en: "Rich chocolate, creamy filling, and crunchy bits that melt in your mouth." } },
  { id: "noodles_red_bean_cream_sushi", price: 3, image: "assets/menu/noodles_red_bean_cream_sushi.webp",
    category: { zh: "招牌卷", py: "Zhāopái Juǎn", en: "Signature Rolls" },
    name:     { zh: "红豆奶油面条寿司", py: "Hóngdòu Nǎiyóu Miàntiáo Shòusī", en: "Noodles Red Bean Cream Sushi" },
    desc:     { zh: "红豆奶油、面条和椰丝，甜软特别。", py: "Hóngdòu nǎiyóu, miàntiáo hé yēsī, tiánruǎn tèbié.", en: "Red bean cream, noodles, and coconut flakes for a sweet, soft surprise." } },
  { id: "banana_chocolate_sushi", price: 3, image: "assets/menu/banana_chocolate_sushi.webp",
    category: { zh: "招牌卷", py: "Zhāopái Juǎn", en: "Signature Rolls" },
    name:     { zh: "香蕉巧克力寿司", py: "Xiāngjiāo Qiǎokèlì Shòusī", en: "Banana Chocolate Sushi" },
    desc:     { zh: "香蕉配巧克力酱，香甜顺滑。", py: "Xiāngjiāo pèi qiǎokèlì jiàng, xiāngtián shùnhuá.", en: "Banana with chocolate drizzle for a smooth dessert-style sushi bite." } },
  { id: "salmon_nigiri", price: 2, image: "assets/menu/salmon_nigiri.webp",
    category: { zh: "经典寿司", py: "Jīngdiǎn Shòusī", en: "Classic Sushi" },
    name:     { zh: "三文鱼握寿司", py: "Sānwényú Wò Shòusī", en: "Salmon Nigiri" },
    desc:     { zh: "新鲜三文鱼放在小团米饭上。", py: "Xīnxiān sānwényú fàng zài xiǎo tuán mǐfàn shàng.", en: "Fresh salmon over a small rice pillow." } },
  { id: "tuna_nigiri", price: 2, image: "assets/menu/tuna_nigiri.webp",
    category: { zh: "经典寿司", py: "Jīngdiǎn Shòusī", en: "Classic Sushi" },
    name:     { zh: "金枪鱼握寿司", py: "Jīnqiāngyú Wò Shòusī", en: "Tuna Nigiri" },
    desc:     { zh: "金枪鱼配软糯米饭，味道清爽。", py: "Jīnqiāngyú pèi ruǎnnuò mǐfàn, wèidào qīngshuǎng.", en: "Tuna served over soft sushi rice for a clean, classic bite." } },
  { id: "shrimp_nigiri", price: 2, image: "assets/menu/shrimp_nigiri.webp",
    category: { zh: "经典寿司", py: "Jīngdiǎn Shòusī", en: "Classic Sushi" },
    name:     { zh: "虾握寿司", py: "Xiā Wò Shòusī", en: "Shrimp Nigiri" },
    desc:     { zh: "鲜虾配寿司饭，口感弹嫩。", py: "Xiānxiā pèi shòusī fàn, kǒugǎn tánnèn.", en: "Tender shrimp over sushi rice." } },
  { id: "cucumber_roll", price: 2, image: "assets/menu/cucumber_roll.webp",
    category: { zh: "经典寿司", py: "Jīngdiǎn Shòusī", en: "Classic Sushi" },
    name:     { zh: "黄瓜卷", py: "Huángguā Juǎn", en: "Cucumber Roll" },
    desc:     { zh: "清脆黄瓜小卷，简单新鲜。", py: "Qīngcuì huángguā xiǎo juǎn, jiǎndān xīnxiān.", en: "A crisp cucumber roll with a clean, fresh crunch." } },
  { id: "avocado_roll", price: 2, image: "assets/menu/avocado_roll.webp",
    category: { zh: "经典寿司", py: "Jīngdiǎn Shòusī", en: "Classic Sushi" },
    name:     { zh: "牛油果卷", py: "Niúyóuguǒ Juǎn", en: "Avocado Roll" },
    desc:     { zh: "奶香牛油果小卷，柔滑清淡。", py: "Nǎixiāng niúyóuguǒ xiǎo juǎn, róuhuá qīngdàn.", en: "Creamy avocado rolled in rice and seaweed." } },
  { id: "crab_roll", price: 2, image: "assets/menu/crab_roll.webp",
    category: { zh: "经典寿司", py: "Jīngdiǎn Shòusī", en: "Classic Sushi" },
    name:     { zh: "蟹肉卷", py: "Xièròu Juǎn", en: "Crab Roll" },
    desc:     { zh: "蟹肉小卷，鲜甜可口。", py: "Xièròu xiǎo juǎn, xiāntián kěkǒu.", en: "A sweet and savory crab roll." } },
  { id: "tempura_shrimp", price: 2, image: "assets/menu/tempura_shrimp.webp",
    category: { zh: "热小吃", py: "Rè Xiǎochī", en: "Hot Snacks" },
    name:     { zh: "天妇罗虾", py: "Tiānfùluó Xiā", en: "Tempura Shrimp" },
    desc:     { zh: "酥脆炸虾，外脆里嫩。", py: "Sūcuì zhá xiā, wài cuì lǐ nèn.", en: "Crispy fried shrimp with a tender inside." } },
  { id: "takoyaki", price: 2, image: "assets/menu/takoyaki.webp",
    category: { zh: "热小吃", py: "Rè Xiǎochī", en: "Hot Snacks" },
    name:     { zh: "章鱼小丸子", py: "Zhāngyú Xiǎowánzi", en: "Takoyaki" },
    desc:     { zh: "章鱼小丸子淋上酱汁和脆片。", py: "Zhāngyú xiǎowánzi lín shàng jiàngzhī hé cuìpiàn.", en: "Saucy octopus bites topped with crispy flakes." } },
  { id: "dumplings", price: 2, image: "assets/menu/dumplings.webp",
    category: { zh: "热小吃", py: "Rè Xiǎochī", en: "Hot Snacks" },
    name:     { zh: "饺子", py: "Jiǎozi", en: "Dumplings" },
    desc:     { zh: "金黄煎饺，热乎多汁。", py: "Jīnhuáng jiān jiǎo, rèhu duōzhī.", en: "Pan-fried dumplings served hot and juicy." } },
  { id: "edamame", price: 2, image: "assets/menu/edamame.webp",
    category: { zh: "热小吃", py: "Rè Xiǎochī", en: "Hot Snacks" },
    name:     { zh: "毛豆", py: "Máodòu", en: "Edamame" },
    desc:     { zh: "清淡毛豆，适合分享。", py: "Qīngdàn máodòu, shìhé fēnxiǎng.", en: "Lightly salted edamame, easy to share." } },
  { id: "mochi_ice_cream", price: 3, image: "assets/menu/mochi_ice_cream.webp",
    category: { zh: "甜点", py: "Tiándiǎn", en: "Sweet Bites" },
    name:     { zh: "麻糬冰淇淋", py: "Máshǔ Bīngqílín", en: "Mochi Ice Cream" },
    desc:     { zh: "软糯麻糬包着冰淇淋。", py: "Ruǎnnuò máshǔ bāo zhe bīngqílín.", en: "Soft mochi wrapped around cool ice cream." } },
  { id: "red_bean_dango", price: 3, image: "assets/menu/red_bean_dango.webp",
    category: { zh: "甜点", py: "Tiándiǎn", en: "Sweet Bites" },
    name:     { zh: "红豆团子", py: "Hóngdòu Tuánzi", en: "Red Bean Dango" },
    desc:     { zh: "红豆甜团子，软糯香甜。", py: "Hóngdòu tián tuánzi, ruǎnnuò xiāngtián.", en: "Sweet red bean dango with a chewy texture." } },
  { id: "chocolate_banana_roll", price: 3, image: "assets/menu/chocolate_banana_roll.webp",
    category: { zh: "甜点", py: "Tiándiǎn", en: "Sweet Bites" },
    name:     { zh: "巧克力香蕉卷", py: "Qiǎokèlì Xiāngjiāo Juǎn", en: "Chocolate Banana Roll" },
    desc:     { zh: "香蕉卷淋巧克力，甜蜜收尾。", py: "Xiāngjiāo juǎn lín qiǎokèlì, tiánmì shōuwěi.", en: "Banana roll drizzled with chocolate for a sweet finish." } },
  { id: "green_tea", price: 1, image: "assets/menu/green_tea.webp",
    category: { zh: "饮料", py: "Yǐnliào", en: "Drinks" },
    name:     { zh: "绿茶", py: "Lǜchá", en: "Green Tea" },
    desc:     { zh: "清香绿茶，解腻清爽。", py: "Qīngxiāng lǜchá, jiěnì qīngshuǎng.", en: "Fragrant green tea, refreshing with sushi." } },
  { id: "lemon_soda", price: 1, image: "assets/menu/lemon_soda.webp",
    category: { zh: "饮料", py: "Yǐnliào", en: "Drinks" },
    name:     { zh: "柠檬汽水", py: "Níngméng Qìshuǐ", en: "Lemon Soda" },
    desc:     { zh: "气泡柠檬饮，酸甜清凉。", py: "Qìpào níngméng yǐn, suāntián qīngliáng.", en: "Sparkling lemon soda, sweet and crisp." } },
  { id: "mango_juice", price: 1, image: "assets/menu/mango_juice.webp",
    category: { zh: "饮料", py: "Yǐnliào", en: "Drinks" },
    name:     { zh: "芒果汁", py: "Mángguǒ Zhī", en: "Mango Juice" },
    desc:     { zh: "香甜芒果汁，果味十足。", py: "Xiāngtián mángguǒ zhī, guǒwèi shízú.", en: "Sweet mango juice with bright fruit flavor." } },
  { id: "water", price: 1, image: "assets/menu/water.webp",
    category: { zh: "饮料", py: "Yǐnliào", en: "Drinks" },
    name:     { zh: "水", py: "Shuǐ", en: "Water" },
    desc:     { zh: "清水，冰凉解渴。", py: "Qīngshuǐ, bīngliáng jiěkě.", en: "Cold water to keep you refreshed." } },
];
